language: python

#which versions of python to test against
python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - pip install codecov
  - pip install coverage




deploy:
  provider: s3
  access_key_id: AKIAJATCVDL32CUPFF4Q
  secret_access_key: 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
  bucket: cps847-6282
  local-dir: website
